### PR TITLE
fixed #133 websocket reconnection

### LINKED ISSUE #133: Reconnect issue after server restart
Hi,

I m trying to use wasync client to establish Websocket connection to another server. And like any production app, we need it to be resilient to server restarts and once server is up, client should reconnect automatically. In one line, **we want always-on connection to server**.

I've written typical program, but still I m facing below issues: 

1. Once I enable `reconnect(true)` option, client is reconnecting to server for the first time, but `REOPEN` event handler function is **NOT** being called. But `STATUS` handler is called with `101` response.
2. If server down again, once the server is up, client is **NOT reconnecting again**.

You can find the project here: https://github.com/manikantag/AtmosphereTest. 
Log file: https://github.com/manikantag/AtmosphereTest/blob/master/log.txt

I've checked multiple times and multiple places, but I m getting if I m doing something wrong. I've also checked the pull request (https://github.com/Atmosphere/wasync/pull/101) for this very issue.

### PR DESCRIPTION
**Pull request by ricardojlrufino**
Fixed reconnection, but has small problem reported in: 
https://github.com/Atmosphere/wasync/issues/133#issuecomment-215951298

> Now the reconnection works, but the first message received on the WebSocket, which looks like atmo id|0|X does not seem to be handled

### CODE REVIEW

**Comment by ricardojlrufino** [comment]
Now firing REOPEN Event.

File: wasync/src/main/java/org/atmosphere/wasync/transport/WebSocketTransport.java [hunk 1]
```diff
@@ -418,7 +427,19 @@ public void onError(Throwable t) {
...
+                if (options.reconnect()) {
+                    close(); // force release resources and reconnect
+                    tryReconnect();
+                }else{
+                    onFailure(new IOException(t.getMessage(), t));
+                }
+            }else{
+                onFailure(t);
+            }
+
```
Comment (slovdahl) [inline wasync/src/main/java/org/atmosphere/wasync/transport/WebSocketTransport.java]: Thank you for your contribution! Could you please reformat this code according to everything else is formatted? Thanks!
